<?php

namespace Eighty\RefiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function registerUser($postdata)
	{
		//var_dump($postdata); exit();
		$this->getEntityManager()->getConnection()
            ->prepare("INSERT INTO 
							client  (
								fullname,
								email,
								password,
								salt
							) 
						VALUES (
							'$postdata[fullname]',
							'$postdata[email]',
							'$postdata[password]',
							'$postdata[salt]'
						)"
					)
			->execute();
	}
}