<?php

namespace Eighty\RefiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function registerUser($postdata)
	{
		//var_dump($postdata); exit();
		$this->getEntityManager()->getConnection()
            ->prepare("INSERT INTO 
							client  (
								fullname,
								email,
								password,
								salt
							) 
						VALUES (
							'$postdata[fullname]',
							'$postdata[email]',
							'$postdata[password]',
							'$postdata[salt]'
						)"
					)
			->execute();
	}

	public function shortlistCredit($postdata)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT t
					FROM RefiBundle:Transactions t
					JOIN RefiBundle:Prospectproperty pp
					WITH t.id = pp.salesId
					WHERE pp.prospectId = :ppId
				'
			)
			->setParameter('ppId', $id)
			->getArrayResult();
	}
}