<?php

namespace Eighty\RefiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectlistRepository extends EntityRepository
{
	public function getProspectList($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT pl.prospectId,
						pl.engaged,
						p.profession,
						p.derivedIncome,
						pl.score,
						pl.status,
						pl.note
					FROM RefiBundle:Prospectlist pl
					JOIN RefiBundle:Prospect p
						WITH pl.prospectId = p.id
					JOIN RefiBundle:Clientlist cl
						WITH cl.id = pl.clientlistId
					WHERE cl.clientId = :uId
				'
			)
			->setParameter('uId', $id)
			->getArrayResult();
	}

}