<?php

namespace Eighty\RefiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectlistRepository extends EntityRepository
{
	public function getProspectList($id, $key)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT pl.prospectId,
						pl.engaged,
						p.profession,
						p.derivedIncome,
						pl.score,
						COUNT(plo.transactionId) AS property_owned,
						pl.status,
						pl.note
					FROM RefiBundle:Prospectlist pl
					JOIN RefiBundle:Prospect p
						WITH pl.prospectId = p.id
					JOIN RefiBundle:Prospectloan plo
						WITH pl.prospectId = plo.prospectId
					JOIN RefiBundle:Clientlist cl
						WITH cl.id = pl.clientlistId
					WHERE cl.clientId = :uId
					AND pl.urakey = :uKey
					GROUP BY pl.prospectId
				'
			)
			->setParameter('uId', $id)
			->setParameter('uKey', $key)
			->getArrayResult();
	}
	
	public function getUrakeyByClient($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT DISTINCT 
					  (pl.urakey) AS urakey
					FROM
					  RefiBundle:Prospectlist pl 
					  JOIN RefiBundle:Clientlist cl 
						WITH cl.id = pl.clientlistId
					WHERE cl.clientId = :uId
				'
			)
			->setParameter('uId', $id)
			->getArrayResult();
	}

}