<?php

namespace Eighty\RefiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends EntityRepository
{
	public function fetchProspectIdsByUrakeyAndSector($urakey, $sector)
	{
		$parameters = array(
				'urakey' => $urakey,
				'sector' => $sector
			);

		return $this->getEntityManager()
			->createQuery(
				'SELECT DISTINCT(pl.prospectId) AS prospectId
					FROM RefiBundle:Prospectloan pl
					JOIN RefiBundle:Transactions t
						WITH pl.transactionId = t.id
					WHERE t.urakey = :urakey
						AND t.sector = :sector
				'
			)
			->setParameters($parameters)
			->getResult();
	}

	public function fetchTransactionsByProspectId($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT t
					FROM RefiBundle:Transactions t
					JOIN RefiBundle:Prospectproperty pp
					WITH t.id = pp.salesId
					WHERE pp.prospectId = :ppId
				'
			)
			->setParameter('ppId', $id)
			->getArrayResult();
	}
}