<?php

namespace Eighty\RefiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends EntityRepository
{
	public function filterProspects($postdata)
	{
		$parameters = array(
				'minIncome' => $postdata['income_min'],
				'maxIncome' => $postdata['income_max'],
				'minDcode' => $postdata['dcode_min'],
				'maxDcode' => $postdata['dcode_max'],
				'minAge' => $postdata['age_min'],
				'maxAge' => $postdata['age_max'],
			);

		return $this->getEntityManager()
			->createQuery(
				'SELECT p
					FROM RefiBundle:Prospect p
					WHERE p.derivedIncome >= :minIncome
						AND p.derivedIncome <= :maxIncome
						AND p.districtcode >= :minDcode
						AND p.districtcode <= :maxDcode
						AND p.age >= :minAge
						AND p.age <= :maxAge
				'
			)
			->setParameters($parameters)
			->setMaxResults($postdata['limit'])
        	->setFirstResult($postdata['offset'])
			->getArrayResult();
	}

	public function fetchTransactionsByProspectId($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT t
					FROM RefiBundle:Transactions t
					JOIN RefiBundle:Prospectproperty pp
					WITH t.id = pp.salesId
					WHERE pp.prospectId = :ppId
				'
			)
			->setParameter('ppId', $id)
			->getArrayResult();
	}
}