imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# cypress_compass_elephant:
#     register_listener: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ RefiBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass:
            bin: "/usr/bin/sass"
        compass:
            bin: "/usr/bin/compass"
        # yui_js:
        #     jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        # yui_css:
        #     jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
