imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    #toolbar: "%debug_toolbar%"
    toolbar: false
    #intercept_redirects: "%debug_redirects%"
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
cypress_compass_elephant:
    register_listener: "%compass_listener%"
    compass_binary_path: "compass"
    compass_projects:
        transactor_assets:
            path: %kernel.root_dir%/../src/Eighty/RefiBundle/Resources/assets/

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%use_assetic_controller%"
    bundles:        [ RefiBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass:
            bin: "/usr/bin/sass"
        compass:
            bin: "/usr/bin/compass"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
#swiftmailer:
#    delivery_address: me@example.com
