refi:
    resource: "@RefiBundle/Resources/config/routing.yml"
    prefix:   /

index:
    pattern:   /
    defaults:  
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /dashboard/
        permanent: true