security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        
    providers:
        main:
            entity:
                class: Eighty\RefiBundle\Entity\Client
                property: email
        in_memory:
            memory: ~
    
    encoders:
        Eighty\RefiBundle\Entity\Client: sha1

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check

                always_use_default_target_path: true
                default_target_path: /dashboard
                
                csrf_provider: form.csrf_provider
                success_handler: security.login.handler
            logout:
                path:   /logout
                target: /login
                invalidate_session: false
                success_handler: security.logout.handler

        default:
            anonymous: ~

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/dashboard, roles: ROLE_USER }
         - { path: ^/campaign, roles: ROLE_USER }
         - { path: ^/calculator, roles: ROLE_USER }
         - { path: ^/report, roles: ROLE_USER }
         - { path: ^/blast, roles: ROLE_USER }
         - { path: ^/list, roles: ROLE_USER }
         - { path: ^/api, roles: ROLE_USER }
         - { path: ^/refi, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         