refi_login:
    pattern: /login/
    defaults: { _controller: RefiBundle:Login:login }

refi_login_check:
    pattern: /login_check

refi_logout:
    pattern: /logout

refi_register:
    pattern: /register/
    defaults: { _controller: RefiBundle:Login:register }

refi_homepage:
    pattern: /dashboard/
    defaults: { _controller: RefiBundle:Application:index }


refi_add:
    pattern: /add/
    defaults: { _controller: RefiBundle:Application:add }


refi_list:
    pattern: /list/
    defaults: { _controller: RefiBundle:Application:list }


refi_calculator:
    pattern: /calculator/
    defaults: { _controller: RefiBundle:Application:calculator }


refi_report:
    pattern: /report/
    defaults: { _controller: RefiBundle:Application:report }



refi_prospect:
    pattern: /prospect/
    defaults: { _controller: RefiBundle:Application:prospect }


API_filter:
    pattern: /api/filter/
    defaults: { _controller: RefiBundle:Application:filter }

API_shortlist:
    pattern: /api/shortlist/
    defaults: { _controller: RefiBundle:Application:shortlist }