refi_login:
    pattern: /login/
    defaults: { _controller: RefiBundle:Login:login }

refi_login_check:
    pattern: /login_check

refi_logout:
    pattern: /logout

refi_register:
    pattern: /register/
    defaults: { _controller: RefiBundle:Login:register }

refi_homepage:
    pattern: /dashboard/
    defaults: { _controller: RefiBundle:Application:index }

refi_campaign:
    pattern: /campaign/
    defaults: { _controller: RefiBundle:Application:campaign }

refi_list:
    pattern: /list/
    defaults: { _controller: RefiBundle:Application:list }

refi_calculator:
    pattern: /calculator/
    defaults: { _controller: RefiBundle:Application:calculator }

refi_report:
    pattern: /report/{id}
    defaults: { _controller: RefiBundle:Application:report, id: 0 }

refi_prospect_report:
    pattern: /refi/report/{hash}
    defaults: { _controller: RefiBundle:Application:prospectreport, hash: 0 }

refi_prospect_report_engage:
    pattern: /refi/engage/{hash}
    defaults: { _controller: RefiBundle:Application:prospectreportengage, hash: 0 }

API_filter_property:
    pattern: /api/filter/property
    defaults: { _controller: RefiBundle:Application:filterProperty }

API_filter_prospect:
    pattern: /api/filter/prospect
    defaults: { _controller: RefiBundle:Application:filterProspect }

API_shortlist_checkout:
    pattern: /api/shortlist/checkout
    defaults: { _controller: RefiBundle:Application:shortlistCheckout }

API_shortlist_blast:
    pattern: /api/shortlist/blast
    defaults: { _controller: RefiBundle:Application:shortlistBlast }

API_shortlist_calculator:
    pattern: /api/shortlist/calculator
    defaults: { _controller: RefiBundle:Application:shortlistCalculator }