refi_login:
    pattern: /login/
    defaults: { _controller: RefiBundle:Login:login }

refi_login_check:
    pattern: /login_check

refi_logout:
    pattern: /logout

refi_register:
    pattern: /register/
    defaults: { _controller: RefiBundle:Login:register }

refi_homepage:
    pattern: /dashboard/
    defaults: { _controller: RefiBundle:Application:index }