refi_login:
    pattern: /login/
    defaults: { _controller: RefiBundle:Login:login }

refi_login_check:
    pattern: /login_check

refi_logout:
    pattern: /logout

refi_register:
    pattern: /register/
    defaults: { _controller: RefiBundle:Login:register }

refi_homepage:
    pattern: /dashboard/
    defaults: { _controller: RefiBundle:Dashboard:index }

refi_campaign:
    pattern: /campaign/
    defaults: { _controller: RefiBundle:Campaign:campaign }

refi_calculator:
    pattern: /calculator/
    defaults: { _controller: RefiBundle:Calculator:calculator }

refi_report:
    pattern: /report/{id}
    defaults: { _controller: RefiBundle:Report:report, id: 0 }

refi_blast_summary:
    pattern: /blast/summary/
    defaults: { _controller: RefiBundle:Report:blastsummary }

refi_prospect_report:
    pattern: /refi/report/{hash}
    defaults: { _controller: RefiBundle:Report:prospectreport, hash: 0 }

refi_list:
    pattern: /list/
    defaults: { _controller: RefiBundle:List:list }

API_report_save:
    pattern: /api/report/save
    defaults: { _controller: RefiBundle:Application:saveandsend }

API_list_update:
    pattern: /api/update_list
    defaults: { _controller: RefiBundle:Application:listupdate }

API_filter_property:
    pattern: /api/filter/property
    defaults: { _controller: RefiBundle:Application:filterProperty }

API_filter_prospect:
    pattern: /api/filter/prospect
    defaults: { _controller: RefiBundle:Application:filterProspect }

API_shortlist_checkout:
    pattern: /api/shortlist/checkout
    defaults: { _controller: RefiBundle:Application:shortlistCheckout }

API_shortlist_blast:
    pattern: /api/shortlist/blast
    defaults: { _controller: RefiBundle:Application:shortlistBlast }

API_shortlist_calculator:
    pattern: /api/shortlist/calculator
    defaults: { _controller: RefiBundle:Application:shortlistCalculator }


refi_test:
    pattern: /test/
    defaults: { _controller: RefiBundle:Application:test }