services:
    security.login.handler:
        class:  %security.login.handler.class%
        arguments:  [@router, @security.context, @doctrine.orm.entity_manager]

    security.logout.handler:
        class:  %security.logout.handler.class%
        arguments:  [@router, @security.context, @doctrine.orm.entity_manager]